@startuml

' an abstract base class for parent selection from a population
abstract class ParentSelector {
  ' select parents from a collections of parents
  ' TODO: figure out the parameters and what to return
  + {abstract} select()
}
ParentSelector <|- ProportionateSelector
ParentSelector <|- LinearRankSelector
ParentSelector <|- TournamentSelector

' a parent selector using proportionate selection approach
class ProportionateParentSelector {
  ' TODO: research the method, document here, flush out this body
}

' a parent selector using linear rank selection approach
class LinearRankParentSelector {
  ' TODO: research the method, document here, flush out this body
}

' a parent selector using tournament selection approah
class TournamentParentSelector {
  ' TODO: research the method, document here, flush out this body
}

@enduml
